In [1]:
import torch
from torch import nn
from torch.nn import functional as F

net = nn.Sequential(nn.Linear(20, 256), nn.ReLU(), nn.Linear(256, 10))

X = torch.rand(2, 20)
net(X)

tensor([[-0.0032,  0.0834, -0.0034, -0.2626, -0.0503, -0.0578,  0.0086, -0.0337,
         -0.1709, -0.1051],
        [ 0.0037,  0.0686, -0.0685, -0.2429,  0.1034,  0.0119, -0.0229, -0.0502,
         -0.1360, -0.1005]], grad_fn=<AddmmBackward0>)

In [3]:
#自定义块
class MLP(nn.Module):
    # 用模型参数声明层。这里，声明两个全连接的层
    def __init__(self):
        # 调用MLP的父类Module的构造函数来执行必要的初始化。
        # 这样，在类实例化时也可以指定其他函数参数，例如模型参数params
        super().__init__()
        self.hidden = nn.Linear(20, 256)  # 隐藏层
        self.out = nn.Linear(256, 10)  # 输出层

    # 定义模型的前向传播，即如何根据输入X返回所需的模型输出
    def forward(self, X):
        return self.out(F.relu(self.hidden(X)))

In [4]:
net = MLP()
net(X)

tensor([[-0.0479, -0.0242,  0.0766,  0.0971, -0.1785,  0.0473, -0.0398,  0.0629,
         -0.0871, -0.0596],
        [-0.0606, -0.0723,  0.0723,  0.0504, -0.1300,  0.0064, -0.0734,  0.1659,
          0.0075, -0.0443]], grad_fn=<AddmmBackward0>)

In [5]:
#自定义层
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [6]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [7]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [9]:
Y = net(torch.rand(4, 8))
print(Y)

tensor([[-1.7996e-01, -1.0267e-02,  9.5267e-02, -1.2180e-01, -3.4127e-01,
         -3.3285e-02, -2.6685e-01, -1.1380e-01,  6.5338e-02,  6.0799e-01,
          2.0657e-01, -1.5468e-01, -6.6768e-01, -3.4184e-01, -1.6016e-01,
          6.5295e-01, -2.1268e-01, -2.3454e-01,  7.1847e-01, -6.0652e-01,
         -2.4792e-01, -2.6870e-01, -2.7777e-01, -6.7275e-01, -1.1908e-01,
          2.8163e-01,  7.2165e-01, -2.7291e-01,  1.0706e-01, -2.7330e-01,
         -1.8959e-01, -3.1010e-02, -2.3547e-01, -4.2721e-02, -7.2180e-01,
          3.4551e-01, -3.4373e-01,  4.5221e-01, -3.6326e-01,  5.3282e-02,
         -2.2542e-01, -7.7740e-03, -4.9194e-01, -3.9410e-01,  5.2417e-01,
          9.8395e-02,  1.2157e-01, -4.1852e-01,  1.4671e-03,  7.5132e-02,
         -4.5669e-01,  4.1758e-02,  1.1511e-01, -3.0402e-02,  5.0816e-01,
          4.0541e-01,  2.3780e-01, -4.0328e-01,  1.5919e-02, -2.5492e-01,
         -5.1630e-01, -1.4718e-02, -1.9579e-01, -5.1256e-01, -2.5013e-01,
         -1.4192e-02, -2.4486e-01, -8.

In [10]:
#带参数的层
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [11]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.7419,  0.6114, -0.7210],
        [ 0.0039,  0.6798,  0.2161],
        [ 0.2227, -0.1355, -0.3872],
        [ 1.6856, -0.5992, -0.9612],
        [ 1.2005,  0.1124,  0.7317]], requires_grad=True)